# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

#
# This file defines paths to key applications for the project
#

#
# Mari
#
mari_linux: 'Mari3.02'
mari_mac: /Applications/Mari3.0v2
mari_windows: 'C:\apps\mari\3.0v2\Bundle\bin\Mari3.0v2.exe'

#
# Maya
#		
maya_windows: 'C:\apps\autodesk\2016\Maya2016\bin\maya.exe'
maya_mac: /Applications/Autodesk/maya2015/Maya.app
maya_linux: maya


#
# nuke
#
nuke_mac: /Applications/Nuke9.0v8/Nuke9.0v8.app
nuke_windows: 'C:\apps\nuke\9.0v8\Nuke9.0.exe'
nuke_linux: Nuke9.0


#
# motionbuilder
#
#motionbuilder_windows: 'C:\Program Files\Autodesk\MotionBuilder 2014\bin\x64\motionbuilder.exe'


#
# 3dsmax 2015
#
#3dsmax_windows: 'C:\Program Files\Autodesk\3ds Max 2015\3dsmax.exe'


#
# Houdini
#
houdini_windows: 'C:\apps\houdini\15.0.347\bin\houdini.exe'
houdini_linux: '/opt/hfs13.0.498/bin/houdini'


#
# photoshop CS6
#
photoshop_mac: /Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app
photoshop_win: 'C:\apps\adobe\cc\Adobe Photoshop CC 2015\Photoshop.exe'
photoshop_extras:
    mac_extension_manager_path: /Applications/Adobe Extension Manager CS6/Adobe Extension Manager CS6.app
    mac_python_path: /usr/bin/python
    windows_extension_manager_path: 'C:\apps\adobe\cc\Adobe Extension Manager CC\Adobe Extension Manager CC.exe'
    windows_python_path: 'C:\Python27\python.exe'


#
# Hiero

hiero_mac: /Applications/Nuke9.0v8/Hiero9.0v7.app/Hiero9.0v7
hiero_win: 'C:\apps\hiero\1.91\hiero.exe'
hiero_linux: /usr/local/Hiero1.9v1/bin/Hiero1.9v1

#
# Softimage
#

#softimage_windows: C:\apps\Autodesk\Softimage 2013\Application\bin\XSI.bat
#softimage_linux: XSI

#
# Tweak RV
#
rv_mac: /Applications/RV64.app
rv_win: C:\apps\rv\6.2.6\bin\rv.exe
rv_linux: rv

