description: Apps and Engines related to Shot based work.
engines:
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-breakdown:
        hook_scene_operations: '{self}/tk-maya_scene_operations.py'
        location: {name: tk-multi-breakdown, type: app_store, version: v1.3.1}
      tk-multi-loader2:
        action_mappings:
          Maya Scene: [reference, import]
          Photoshop Image: [texture_node]
          Rendered Image: [texture_node]
          Yeti Sim Nodes : [reference_version, reference_master]
        actions_hook: '{config}/loader/mds-tk-maya_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: Shots
          entity_type: Shot
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location: {name: tk-multi-loader2, type: app_store, version: v1.7.1}
        menu_name: Load
        publish_filters: []
        title_name: Loader
      tk-multi-publish:
        allow_taskless_publishes: true
        display_name: Publish
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.6.10}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs:
        - description: Copy renders from work area to publish area.
          display_group: Renders
          display_name: Rendered
          icon: icons/publish_nuke_writenode.png
          name: maya_rendered_image
          publish_template: maya_shot_render_pub
          required: true
          scene_item_type: maya_rendered_image
          selected: true
          tank_type: Maya Rendered Image
        template_work: maya_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.2.4}
        sg_in_frame_field: sg_head_in
        sg_out_frame_field: sg_tail_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.4.1}
        template_snapshot: maya_shot_snapshot
        template_work: maya_shot_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: true
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.6.15}
        saveas_default_name: ''
        saveas_prefer_version_up: true
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Shot, Asset]
        sg_task_filters: []
        task_extra_display_fields: []
        template_publish: maya_shot_publish
        template_publish_area: shot_publish_area_maya
        template_work: maya_shot_work
        template_work_area: shot_work_area_maya
        version_compare_ignore_fields: []
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.5.1}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    template_project: shot_work_area_maya
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-breakdown:
        hook_scene_operations: '{self}/tk-nuke_scene_operations.py'
        location: {name: tk-multi-breakdown, type: app_store, version: v1.3.1}
      tk-multi-loader2:
        action_mappings:
          Nuke Script: [script_import]
          Rendered Image: [read_node]
          Maya Rendered Image: [read_node]
        actions_hook: '{self}/tk-nuke_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: Shots
          entity_type: Shot
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location: {name: tk-multi-loader2, type: app_store, version: v1.7.1}
        menu_name: Load
        publish_filters: []
        title_name: Loader
      tk-multi-publish:
        allow_taskless_publishes: true
        display_name: Publish
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.6.10}
        primary_description: Publishes and versions up the current Nuke script.
        primary_display_name: Nuke Publish
        primary_icon: icons/publish_nuke_main.png
        primary_publish_template: nuke_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Nuke Script
        secondary_outputs:
        - {description: Copy renders from work area to publish area., display_group: Shotgun
            Write Nodes, display_name: Publish Renders, icon: icons/publish_nuke_writenode.png,
          name: render, publish_template: null, required: false, scene_item_type: write_node,
          selected: true, tank_type: Rendered Image}
        - {description: Create quicktime and send to Screening Room, display_group: Shotgun
            Write Nodes, display_name: Send to Screening Room, icon: icons/publish_nuke_review.png,
          name: quicktime, publish_template: null, required: false, scene_item_type: write_node,
          selected: true, tank_type: Quicktime}
        template_work: nuke_shot_work
      tk-multi-reviewsubmission:
        location: {name: tk-multi-reviewsubmission, type: app_store, version: v0.1.12}
        movie_height: 540
        movie_path_template: nuke_shot_render_movie
        movie_width: 1024
        new_version_status: rev
        slate_logo: icons/review_submit_logo.png
        store_on_disk: true
        upload_to_shotgun: true
        version_number_padding: 3
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.2.4}
        sg_in_frame_field: sg_head_in
        sg_out_frame_field: sg_tail_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.4.1}
        template_snapshot: nuke_shot_snapshot
        template_work: nuke_shot_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.6.15}
        saveas_default_name: ''
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Shot, Asset]
        sg_task_filters: []
        task_extra_display_fields: []
        template_publish: nuke_shot_publish
        template_publish_area: shot_publish_area_nuke
        template_work: nuke_shot_work
        template_work_area: shot_work_area_nuke
        version_compare_ignore_fields: []
      tk-nuke-quickdailies:
        current_scene_template: nuke_shot_work
        height: 768
        location: {name: tk-nuke-quickdailies, type: app_store, version: v0.1.8}
        movie_template: shot_quicktime_quick
        post_hooks: [snapshot_history_post_quickdaily, nuke_quickdailies_upload_movie]
        sg_version_name_template: nuke_quick_shot_version_name
        width: 1024
      tk-nuke-writenode:
        location: {name: tk-nuke-writenode, type: app_store, version: v1.0.15}
        template_script_work: nuke_shot_work
        write_nodes:
        - file_type: exr
          name: Publish to Exr
          proxy_publish_template: null
          proxy_render_template: null
          publish_template: nuke_shot_render_pub_exr
          render_template: nuke_shot_render_stereo
          settings: {datatype: 16 bit half}
          tank_type: Rendered Image
          tile_color: []
        - file_type: exr
          name: Precomp Node
          proxy_publish_template: null
          proxy_render_template: null
          publish_template: nuke_shot_precomp_exr
          render_template: nuke_shot_precomp_exr
          settings: {datatype: 16 bit half}
          tank_type: Rendered Image
          tile_color: []
    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location: {name: tk-nuke, type: app_store, version: v0.3.1}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps:
      tk-multi-about: '@about'
      tk-multi-loader2:
        action_mappings:
          Photoshop Image: [add_as_a_layer, open_file]
          Rendered Image: [add_as_a_layer, open_file]
        actions_hook: '{self}/tk-photoshop_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: Shots
          entity_type: Shot
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location: {name: tk-multi-loader2, type: app_store, version: v1.7.1}
        menu_name: Load
        publish_filters: []
        title_name: Loader
      tk-multi-publish:
        allow_taskless_publishes: true
        display_name: Publish
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.6.10}
        primary_description: Publish and version up the current Photoshop scene
        primary_display_name: Photoshop Publish
        primary_icon: icons/publish_photoshop_main.png
        primary_publish_template: photoshop_shot_publish
        primary_scene_item_type: work_file
        primary_tank_type: Photoshop Image
        secondary_outputs: []
        template_work: photoshop_shot_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.4.1}
        template_snapshot: photoshop_shot_snapshot
        template_work: photoshop_shot_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.6.15}
        saveas_default_name: ''
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Shot, Asset]
        sg_task_filters: []
        task_extra_display_fields: []
        template_publish: photoshop_shot_publish
        template_publish_area: shot_publish_area_photoshop
        template_work: photoshop_shot_work
        template_work_area: shot_work_area_photoshop
        version_compare_ignore_fields: []
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.3.2}
  tk-shell:
    apps: {tk-multi-about: '@about', tk-multi-launchmaya: '@launch_maya', tk-multi-launchnuke: '@launch_nuke',
      tk-multi-screeningroom: '@launch_screeningroom'}
    location: {name: tk-shell, type: app_store, version: v0.4.1}
frameworks:
  tk-framework-shotgunutils_v1.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v1.0.10}
  tk-framework-softimageqt_v1.0.1:
    location: {name: tk-framework-softimageqt, type: app_store, version: v1.0.1}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
  tk-framework-widget_v0.1.22:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.22}
includes: [./includes/app_launchers.yml, ./includes/common_apps.yml]
